language: python
python:
    - "3.6"

services:
    #Just docker because all the "sub-services" will be contained in the docker file.
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "python manage.py test && flake8"
